name: cats-par
baseurl: /cats-par
description: Single Type Parameter Parallel Instances
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.1-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
